const TechToLink = {
    React: "https://react.dev/",
    Javascript: "https://en.wikipedia.org/wiki/JavaScript",
    Python: "https://www.python.org/",
    NGINX: "https://nginx.org/en/",
    SnipsAI: "https://snips.ai/",
    C: "https://en.wikipedia.org/wiki/C_(programming_language)",
    CPlusPlus: "https://en.wikipedia.org/wiki/C%2B%2B",
    Kusto: "https://learn.microsoft.com/en-us/kusto/?view=microsoft-fabric",
    SQL: "https://en.wikipedia.org/wiki/SQL",
    WinDBG: "https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/",
    WPA: "https://learn.microsoft.com/en-us/windows-hardware/test/wpt/windows-performance-analyzer",
    Azure: "https://azure.microsoft.com/en-us",
    Foundry: "https://foundryvtt.com/",
    Inkarnate: "https://inkarnate.com/",
    WorldAnvil: "https://www.worldanvil.com/",
    StreamDeck: "https://www.elgato.com/us/en/p/stream-deck-mk2-black",
    Obsidian: "https://obsidian.md/",
    Unity: "https://unity.com/",
    CSharp: "https://en.wikipedia.org/wiki/C_Sharp_(programming_language)",
    SourceFilmMaker: "https://www.sourcefilmmaker.com/",
    Hammer: "https://developer.valvesoftware.com/wiki/Valve_Hammer_Editor_(Source_2)",
    Source2: "https://en.wikipedia.org/wiki/Source_2",
    ChroMapper: "https://github.com/Caeden117/ChroMapper",
    NodeJS: "https://nodejs.org/en",
    ElevenLabs: "https://elevenlabs.io/",
    CoquiTTS: "https://github.com/coqui-ai/TTS",
    Unreal5: "https://www.unrealengine.com/en-US/unreal-engine-5",
    Blueprints: "https://dev.epicgames.com/documentation/en-us/unreal-engine/blueprints-visual-scripting-in-unreal-engine",
    SASS: "https://sass-lang.com/",
    Godot: "https://godotengine.org/",
    HLSL: "https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl",
    Twitch: "https://dev.twitch.tv/docs/api/",
    MVVM: "https://dev.epicgames.com/documentation/en-us/unreal-engine/umg-viewmodel-for-unreal-engine#create-instance"
}

export {
    TechToLink,
}